// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0Qfcotr4-klZJ3crQzC-YOW_-tZgY4zI',
    appId: '1:511025579846:web:8e5a409edb8d71407d4747',
    messagingSenderId: '511025579846',
    projectId: 'store-6965c',
    authDomain: 'store-6965c.firebaseapp.com',
    storageBucket: 'store-6965c.firebasestorage.app',
    measurementId: 'G-DSSFMKE0X3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZEJ1YA1odUbeUMKoSsUQuNF_-Rv5Tlus',
    appId: '1:511025579846:android:7458313853ad6c207d4747',
    messagingSenderId: '511025579846',
    projectId: 'store-6965c',
    storageBucket: 'store-6965c.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC0Qfcotr4-klZJ3crQzC-YOW_-tZgY4zI',
    appId: '1:511025579846:web:096a544e048ad08f7d4747',
    messagingSenderId: '511025579846',
    projectId: 'store-6965c',
    authDomain: 'store-6965c.firebaseapp.com',
    storageBucket: 'store-6965c.firebasestorage.app',
    measurementId: 'G-4MF4DH70YY',
  );
}
